name: flutter_responsive_web
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  beamer: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: pretendard
      fonts:
        - asset: fonts/regular.otf
          weight: 400
        - asset: fonts/medium.otf
          weight: 500
        - asset: fonts/semibold.otf
          weight: 600
        - asset: fonts/bold.otf
          weight: 700
